title: G4l1l30
description: >-
  Another Writeups/InfoSec Blog <a
  href="https://github.com/g4l1l30sec" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: America/Santo_Domingo
image: 
repo: 'https://github.com/piharpi/jekyll-klise'
mode: dark
author:
  name: G4l1l30
  bio: |
    Another Writeups/InfoSec Blog.
    Tolkiendil :) ;& [blank repo] at <a href="https://github.com/g4l1l30sec" target="_blank" rel="noopener">@github</a>.
    ctf player at <a href="https://www.hackthebox.eu/profile/321601" target="_blank" rel="noopener">Hack The Box</a>.
  username: username
  github: g4l1l30sec
  twitter: https://twitter.com/G4l1l302
  facebook: 0xNoP
  email: your-email@email.com
  avatar: /assets/img/avatar.jpg
url: 'https://g4l1l30sec.github.io/'
baseurl: ''
permalink: '/:title/'
google_analytics: null
fb_appid: null
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false
jekyll_compose:
  post_default_front_matter:
    modified: null
    tags: []
    description: null
  draft_default_front_matter:
    modified: null
    tags: []
    description: null
number_of_posts: 5
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
